# configuration.yaml - 05.04.2018-a

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml
 
# introduction:
# cloud:

automation: !include_dir_merge_list config/etc/automation
config:
conversation:
discovery:
frontend:
group: !include_dir_merge_named config/interface/group
http:
hue:
  bridges:
    - host: !secret hue_ip
      allow_unreachable: true
      allow_hue_groups: true
map:
mqtt:
  broker: core-mosquitto
  username: !secret mqtt_id
  password: !secret mqtt_pw
script: !include scripts.yaml
sun:
tts:
  - platform: google
updater:
  include_used_components: true

# Tracking - Logging
history:
recorder: !include config/core/recorder.yaml
logbook: !include config/core/logbook.yaml

## My components/devices/sensors/etc ##
sensor: !include_dir_merge_list config/component/sensor
switch: !include_dir_merge_list config/component/switch
binary_sensor: !include_dir_merge_list config/component/binarysensor
device_tracker: !include_dir_merge_list config/component/devicetracker
##
