homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Berlin
  customize: !include customize.yaml
 
# introduction:
# cloud:

automation: !include_dir_merge_list config/etc/automation
config:
conversation:
discovery:
duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token
frontend:
group: !include_dir_merge_named config/interface/group
http:
  api_password: !secret hass_http_api_pw
  # CORS access is optional
  #cors_allowed_origins:
  #  - https://reformedreality.com
  #  - http://reformedreality.com
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.0.0/24
    - 192.168.178.0/24
hue:
  bridges:
    - host: !secret hue_ip
      allow_unreachable: true
      allow_hue_groups: true
map:
media_player:
  - platform: sonos
#mqtt:
#  broker: core-mosquitto
#  username: !secret mqtt_id
#  password: !secret mqtt_pw
#notify:
#  - name: Mastodon
#    platform: mastodon
#    access_token: !secret mastodon_token
#    client_id: !secret mastodon_id
#    client_secret: !secret mastodon_secret
#    base_url: !secret mastodon_baseurl
panel_iframe:
  nodered:
    title: 'Node-Red'
    icon: 'mdi:shuffle-variant'
    url: 'http://127.0.0.1:1880/'

script: !include scripts.yaml
sun:
tts:
  - platform: google
updater:
  include_used_components: true
zwave:
  usb_path: /dev/ttyACM0
  network_key: !secret zwave_key

# Tracking - Logging
history:
recorder: !include config/core/recorder.yaml
logbook: !include config/core/logbook.yaml

## My components/devices/sensors/etc ##
sensor: !include_dir_merge_list config/component/sensor
switch: !include_dir_merge_list config/component/switch
binary_sensor: !include_dir_merge_list config/component/binarysensor
device_tracker: !include_dir_merge_list config/component/devicetracker
##
