- platform: pi_hole
  host: !secret pi2vpnhole_ip
  monitored_conditions:
    - ads_blocked_today
    - ads_percentage_today
    - dns_queries_today
    - unique_domains
    - domains_being_blocked
    - unique_clients
    - queries_forwarded
