- platform: snmp
  host: !secret switch_ip
  name: Zyxel Switch Uptime
  version: 2c
  community: hass
  accept_errors: true
  baseoid: 1.3.6.1.2.1.1.3.0
  unit_of_measurement: 'minutes'
  value_template: '{{((value | int) / 6000) | int}}'
