- platform: waze_travel_time
  name: Heimat
  origin: !secret ort_su
  destination: !secret ort_heimat
  region: 'EU'
  
- platform: waze_travel_time
  name: CGN-EIN
  origin: !secret ort_cgn
  destination: !secret ort_ein
  region: 'EU'
  
- platform: waze_travel_time
  name: EIN-CGN
  origin: !secret ort_ein
  destination: !secret ort_cgn
  region: 'EU'
