auto:
  name: Auto
  view: yes
  icon: mdi:car
  entities:
    - group.fuel
    - group.traveltime
    
fuel:
  name: Kraftstoffkosten
  entities:
    - sensor.mundorf_e10
    - sensor.zeithstr_e10
    
traveltime:
  name: Fahrzeiten
  entities:
    - sensor.fahrzeit_suhome
    - sensor.heimat
    - sensor.fahrzeit_homesu
    - sensor.fahrzeit_cgnein
    - sensor.cgnein
    - sensor.fahrzeit_eincgn
    - sensor.eincgn
