hardwareinfo:
  name: Hardware Info
  view: yes
  icon: mdi:chip
  entities:
    - group.pi1
    - group.pi2
    - group.pi3
    
pi1:
  name: Hardware Pi1 PiHole DNSoverTLS
  entities:
    - device_tracker.piholepi1
    - sensor.pi1hole
    - sensor.pi1_netdata_uptime
    - sensor.pi1_netdata_system_load
    - sensor.pi1_netdata_ram_used
    - sensor.pi1_netdata_ram_free
    - sensor.pi1_netdata_swap_used
    - sensor.pi1_netdata_swap_free
    - sensor.pihole_1_dns_queries_today
    - sensor.pihole_1_dns_queries_forwarded
    - sensor.pihole_1_ads_blocked_today
    - sensor.pihole_1_ads_percentage_blocked_today
    - sensor.pihole_1_dns_unique_clients
    - sensor.pihole_1_dns_unique_domains
    - sensor.pihole_1_domains_blocked
    
pi2:
  name: Hardware Pi2 PiHole-OpenVPN
  entities:
    - device_tracker.pi2
    - sensor.pi2
    - sensor.pi2_netdata_uptime
    - sensor.pi2_netdata_system_load
    - sensor.pi2_netdata_ram_used
    - sensor.pi2_netdata_ram_free
    - sensor.pi2_netdata_swap_used
    - sensor.pi2_netdata_swap_free
    - sensor.pihole_2_dns_queries_today
    - sensor.pihole_2_dns_queries_forwarded
    - sensor.pihole_2_ads_blocked_today
    - sensor.pihole_2_ads_percentage_blocked_today
    - sensor.pihole_2_dns_unique_clients
    - sensor.pihole_2_dns_unique_domains
    - sensor.pihole_2_domains_blocked
    
pi3:
  name: Hardware Pi3 HomeAssistant
  entities:
    - sensor.ha_uptime
    - sensor.last_boot
    - sensor.since_last_boot
    - sensor.load_1m
    - sensor.load_5m
    - sensor.load_15m
    - sensor.processor_use
    - sensor.memory_use
    - sensor.memory_free
    - sensor.memory_use_percent
    - sensor.swap_use_percent
