hardwareinfo:
  name: Hardware Info
  view: yes
  icon: mdi:chip
  entities:
    - group.homeautomation
    - group.hardware
    - group.hardware_mobil
    - group.hardware_streaming
    - group.pihole
    
homeautomation:
  name: Home Automation
  entities:
    - sensor.alexa
    - sensor.googlehome
    - sensor.googlehomemini
    - sensor.huelightshub
    - sensor.ikealightshub   

hardware:
  name: Hardware
  entities:
    - sensor.chromebox
    - sensor.acerdesktop
    - sensor.pi1hole
    - sensor.epsonbx525wd
    - sensor.freifunkrouter

hardware_mobil:
  name: Hardware - Mobil
  entities:
    - sensor.medionpad
    - sensor.amazonfire7
    - sensor.nexus6p
    - sensor.surfacebw
    
hardware_streaming:
  name: Hardware - TV & Streaming
  entities:
    - sensor.samsungtv
    - sensor.ccvideotv
    - sensor.firesticktvsu
    - sensor.ccaudiokuche
    
pihole:
  name: Hardware - pi1Hole
  entities:    
    - sensor.pi1hole
    - sensor.pi1hole_netdata_uptime
    - sensor.pihole_dns_queries_today
    - sensor.pihole_ads_blocked_today
    - sensor.pihole_dns_queries_forwarded
    - sensor.pihole_dns_unique_clients
    - sensor.pi1hole_netdata_system_load
    - sensor.pi1hole_netdata_ram_used
    - sensor.pi1hole_netdata_swap_used
