hardwareinfo:
  name: Hardware Info
  view: yes
  icon: mdi:chip
  entities:
    - group.homeautomation
    - group.hardware
    - group.hardware_mobil
    - group.hardware_streaming
    - group.pihole
    - group.pihassio
    
homeautomation:
  name: Home Automation
  entities:
    - sensor.alexa
    - sensor.googlehome
    - sensor.googlehomemini
    - sensor.huelightshub
    - sensor.ikealightshub   

hardware:
  name: Hardware
  entities:
    - sensor.chromebox
    - sensor.acerdesktop
    - sensor.pi1hole
    - sensor.epsonbx525wd
    - sensor.freifunkrouter

hardware_mobil:
  name: Hardware - Mobil
  entities:
    - sensor.medionpad
    - sensor.amazonfire7
    - sensor.nexus6p
    - sensor.surfacebw
    
hardware_streaming:
  name: Hardware - TV & Streaming
  entities:
    - sensor.samsungtv
    - sensor.ccvideotv
    - sensor.firesticktvsu
    - sensor.ccaudiokuche
    
pihole:
  name: Hardware - Pi2 piHoleVPN
  entities:    
    - sensor.pi1hole
    - sensor.pi2vpnhole_netdata_uptime
    - sensor.pihole_dns_queries_today
    - sensor.pihole_ads_blocked_today
    - sensor.pihole_dns_queries_forwarded
    - sensor.pihole_dns_unique_clients
    - sensor.pi2vpnhole_netdata_system_load
    - sensor.pi2vpnhole_netdata_ram_used
    - sensor.pi2vpnhole_netdata_swap_used

pihassio:
  name: Hardware - pi3Hassio
  entities:    
    - sensor.last_boot
    - sensor.since_last_boot
    - sensor.memory_use
    - sensor.memory_use_percent
    - sensor.swap_use_percent
    - sensor.load_1m
    - sensor.load_5m
    - sensor.load_5m
    - sensor.processor_use
