online:
  name: Who is online
  view: yes
  icon: mdi:network
  entities:
    - group.homeautomation
    - group.minipc
    - group.hardware
    - group.hardware_mobil
    - group.hardware_streaming
    
homeautomation:
  name: Home Automation
  entities:
    - sensor.alexa
    - sensor.googlehome
    - sensor.googlehomemini
    - sensor.huelightshub
    - sensor.ikealightshub

hardware:
  name: Hardware
  entities:
    - sensor.chromebox
    - sensor.acerlaptop
    - sensor.epsonbx525wd
    - sensor.freifunkrouter
    - sensor.arcospad
    - sensor.360cam
    - sensor.zyxelswitch
    - sensor.zyxel_switch_uptime

minipc:
  name: Pi's
  entities:
    - sensor.odroid
    - sensor.pi1hole
    - sensor.pi1munin
    - sensor.pi2
    - sensor.pi3hass
    
hardware_mobil:
  name: Hardware - Mobil
  entities:
    - sensor.medionpad
    - sensor.amazonfire7
    - sensor.nexus6p
    - sensor.surfacebw
    
hardware_streaming:
  name: Hardware - TV & Streaming
  entities:
    - sensor.samsungtv
    - sensor.ccvideotv
    - sensor.firesticktvsu
    - sensor.ccaudiokuche
    - sensor.sonosbridge
