steckdosen:
  name: Steckdosen
  view: yes
  icon: mdi:power-plug
  entities:
    - group.fritzkuchemitte
    - group.fritzkucherechts
    - group.fritzkucheoben
    - group.fritzofficelinks
    - group.fritzofficemitte
    - group.fritzofficerechts
    - group.fritzassistenten
    - group.fritztv
    - group.fritzbed
    - group.osramplugs
    - group.zwaveplugs
    
fritzkuchemitte:
  name: Küche Mitte
  entities:
    - switch.balkontur
    - sensor.fritzbalkonturwatt
    - sensor.fritzbalkonturkwh
    - sensor.fritzbalkonturtemp
    
fritzkucherechts:
  name: Küche Rechts
  entities:
    - switch.kuche_rechts
    - sensor.fritzkucherechtswatt
    - sensor.fritzkucherechtskwh
    - sensor.fritzkucherechtstemp

fritzkucheoben:
  name: Küche Oben
  entities:
    - switch.kuche_oben
    - sensor.fritzkucheobenwatt
    - sensor.fritzkucheobenkwh
    - sensor.fritzkucheobentemp
    
fritzofficelinks:
  name: Büro Links
  entities:
    - switch.office_links
    - sensor.fritzofficelinkswatt
    - sensor.fritzofficelinkskwh
    - sensor.fritzofficelinkstemp
    
fritzofficemitte:
  name: Büro Mitte
  entities:
    - switch.office_mitte
    - sensor.fritzofficemittewatt
    - sensor.fritzofficemittekwh
    - sensor.fritzofficemittetemp
    
fritzofficerechts:
  name: Büro Rechts
  entities:
    - switch.office_rechts
    - sensor.fritzofficerechtswatt
    - sensor.fritzofficerechtskwh
    - sensor.fritzofficerechtstemp
    
fritzassistenten:
  name: Assistenten
  entities:
    - switch.assistenten
    - sensor.fritzassistentenwatt
    - sensor.fritzassistentenkwh
    - sensor.fritzassistententemp
    
fritzbed:
  name: Schlafzimmer
  entities:
    - switch.bed
    - sensor.fritzbedwatt
    - sensor.fritzbedkwh
    - sensor.fritzbedtemp
    
fritztv:
  name: TV
  entities:
    - switch.tv
    - sensor.fritztvwatt
    - sensor.fritztvkwh
    - sensor.fritztvtemp
    
osramplugs:
  name: Osram Plugs
  entities:
    - light.steckdose_wohzimmer
    - light.steckdose_2
    - light.steckdose_3
    - light.onoff_plug_1
    - light.onoff_plug_1_2

zwaveplugs:
  name: Zwave Plugs
  entities:
    - switch.switch_3
