# Kitchen - switch blue LED-stripes: on at sunset / off 22:00 / daily
# Bedroom - switch LED-stripes: on at sunset / off 22:00 / daily
# B端roturm - switchon at sunset / off 24:00 / daily
# Wohnzimmertisch - switchon at sunset / off 24:00 / daily
# 29.05.2018-a
#
- alias: LED K端che/Bed An
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
#    offset: "+00:30:00"
  action:
    - service: switch.turn_on
      entity_id: switch.kuche_oben
    - service: light.turn_on
      entity_id: light.steckdose_4
    - service: light.turn_on
      entity_id: light.buroturm
    - service: light.turn_on
      entity_id: light.wohnzimmertisch

- alias: LED K端che/Bed Aus
  initial_state: True
  hide_entity: False
  trigger:
    platform: time
    at: "22:00:00"
  action:
    - service: switch.turn_off
      entity_id: switch.kuche_oben
    - service: light.turn_off
      entity_id: light.steckdose_4
      
- alias: B端roturm Aus
  initial_state: True
  hide_entity: False
  trigger:
    platform: time
    at: "23:59:59"
  action:
    - service: light.turn_off
      entity_id: light.buroturm
    - service: light.turn_off
      entity_id: light.wohnzimmertisch
