# Kitchen - switch blue LED-stripes: on at sunset / off 22:00 / daily
# Bedroom - switch LED-stripes: on at sunset / off 22:00 / daily
# 27.04.2018-a
#
- alias: LED Küche/Bed An
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunset
#    offset: "+00:30:00"
  action:
    - service: switch.turn_on
      entity_id: switch.kuche_oben
    - service: light.turn_on
      entity_id: light.steckdose_4

- alias: LED Küche/Bed Aus
  initial_state: True
  hide_entity: False
  trigger:
    platform: time
    at: "22:00:00"
  action:
    - service: switch.turn_off
      entity_id: switch.kuche_oben
    - service: light.turn_off
      entity_id: light.steckdose_4
