purge_keep_days: 14
exclude:
  domains:
    - automation
    - updater
  entities:
    - sun.sun
    - binary_sensor.workday_sensor
    - sensor.yr_symbol
    - sensor.dark_sky_apparent_temperature
    - sensor.dark_sky_daily_high_temperature
    - sensor.dark_sky_daily_low_temperature
    - sensor.dark_sky_dew_point
    - sensor.dark_sky_hourly_summary
    - sensor.dark_sky_icon
    - sensor.dark_sky_nearest_storm_distance
    - sensor.dark_sky_precip
    - sensor.fritzbox_su
    - sensor.ha_uptime
    - sensor.last_boot
    - sensor.memory_free
    - sensor.memory_use_percent
    - sensor.pihole_ads_percentage_blocked_today
    - sensor.pihole_dns_queries_today
    - sensor.pihole_dns_unique_domains
    - sensor.since_last_boot
    - sensor.swap_use_percent
